name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Lime
      run: |
        sudo apt-get update
        sudo apt-get install neko
        sudo haxelib setup
        haxelib install lime
        export PATH=$PATH:~/.haxelib/lime/<version>/tools
      shell: bash
    - name: Build APK
      run: |
        cd /github/workspace
        lime build android -release
      shell: bash
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Debug.apk
        path: export/android/release/bin/MyGame-release.apk
