name: Build Android APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Haxe/OpenFL
        uses: openfl/setup-haxe@v1.5.1
        with:
          haxe-version: '4.2.3'
          openfl-version: '9.1.0'
          lime-version: '7.9.0'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: openfl build android

      - name: Generate APK
        run: |
          cd export/android/bin
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore /path/to/keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }} app-release-unsigned.apk alias_name
          zipalign -v 4 app-release-unsigned.apk app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: export/android/bin/app-release.apk
